
exports.getData = function (method, data) {
    var returnData = {
        "retCode": "00",
        "retMsg": "成功",
        "tid": "424.17238723089950000",
        "retList": [
            {
                "matAttribute": "0",
                "totalAmount": 2050000,
                "shelfId": "C399999-01-01-01",
                "shelfStatus": 1,
                "qfFlag": "1",
                "shelfType": 0,
                "switchStatus": "1",
                "detail": [
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-01-01",
                        "entityCatalog": 1,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 5,
                        "cellId": "A01-001-01-01",
                        "remoteCellId": "L-1-1",
                        "cellType": 1,
                        "cellStatus": 3,
                        "locationId": "3",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 50000,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [
                            {
                                "containerId": null,
                                "matId": "01",
                                "matName": "人民币",
                                "propertySkuId": "K05|G0|H02|S00|E17",
                                "matSkuId": "00017",
                                "matCount": 1000,
                                "cashProperty": 0,
                                "amount": 50.0,
                                "propertyDetail": "[{\"name\":\"套别\",\"value\":\"第五套\",\"id\":\"K05\"},{\"name\":\"票面\",\"value\":\"正常币\",\"id\":\"G0\"},{\"name\":\"版别\",\"value\":\"19版\",\"id\":\"H02\"},{\"name\":\"材质\",\"value\":\"普通币纸币\",\"id\":\"S00\"},{\"name\":\"券别\",\"value\":\"50元\",\"id\":\"E17\"}]",
                                "bindTime": "20240726103934",
                                "cashNo": "E17",
                                "cashName": null,
                                "cashNote": null,
                                "cashNoteName": null,
                                "cashBan": null,
                                "cashBanName": null,
                                "cashTao": null,
                                "cashTaoName": null,
                                "cashAttribute": null,
                                "cashAttributeName": null,
                                "totalAmount": null,
                                "jnbProductNo": null,
                                "jnbProductName": null,
                                "matSource": null,
                                "entityCatalog": null
                            }
                        ],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-07-26 10:39:41",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-03-03",
                        "entityCatalog": 1,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 5,
                        "cellId": "A01-001-03-03",
                        "remoteCellId": "L-3-3",
                        "cellType": 1,
                        "cellStatus": 2,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 800000,
                        "boxWeight": "1100",
                        "imagePath": "http://192.168.100.104:9000/system/20240726104142060.jpg",
                        "aiImage": "http://192.168.100.104:9000/system/20240726104142559.jpg",
                        "note": "",
                        "matSkus": [
                            {
                                "containerId": null,
                                "matId": "01",
                                "matName": "人民币",
                                "propertySkuId": "K05|G0|H03|S00|E18",
                                "matSkuId": "00020",
                                "matCount": 8000,
                                "cashProperty": 0,
                                "amount": 100.0,
                                "propertyDetail": "[{\"name\":\"套别\",\"value\":\"第五套\",\"id\":\"K05\"},{\"name\":\"票面\",\"value\":\"正常币\",\"id\":\"G0\"},{\"name\":\"版别\",\"value\":\"15版\",\"id\":\"H03\"},{\"name\":\"材质\",\"value\":\"普通币纸币\",\"id\":\"S00\"},{\"name\":\"券别\",\"value\":\"100元\",\"id\":\"E18\"}]",
                                "bindTime": "20240726104140",
                                "cashNo": "E18",
                                "cashName": null,
                                "cashNote": null,
                                "cashNoteName": null,
                                "cashBan": null,
                                "cashBanName": null,
                                "cashTao": null,
                                "cashTaoName": null,
                                "cashAttribute": null,
                                "cashAttributeName": null,
                                "totalAmount": null,
                                "jnbProductNo": null,
                                "jnbProductName": null,
                                "matSource": null,
                                "entityCatalog": null
                            }
                        ],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-07-26 10:41:42",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-03-02",
                        "entityCatalog": 1,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 3,
                        "cellId": "A01-001-03-02",
                        "remoteCellId": "L-2-3",
                        "cellType": 1,
                        "cellStatus": 3,
                        "locationId": "1",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 1200000,
                        "boxWeight": "1100",
                        "imagePath": "http://192.168.100.104:9000/system/20240725103232519.jpg",
                        "aiImage": "http://192.168.100.104:9000/system/20240725103232877.jpg",
                        "note": "",
                        "matSkus": [
                            {
                                "containerId": null,
                                "matId": "01",
                                "matName": "人民币",
                                "propertySkuId": "K05|G0|H03|S00|E18",
                                "matSkuId": "00020",
                                "matCount": 12000,
                                "cashProperty": 0,
                                "amount": 100.0,
                                "propertyDetail": "[{\"name\":\"套别\",\"value\":\"第五套\",\"id\":\"K05\"},{\"name\":\"票面\",\"value\":\"正常币\",\"id\":\"G0\"},{\"name\":\"版别\",\"value\":\"15版\",\"id\":\"H03\"},{\"name\":\"材质\",\"value\":\"普通币纸币\",\"id\":\"S00\"},{\"name\":\"券别\",\"value\":\"100元\",\"id\":\"E18\"}]",
                                "bindTime": "20240725103231",
                                "cashNo": "E18",
                                "cashName": null,
                                "cashNote": null,
                                "cashNoteName": null,
                                "cashBan": null,
                                "cashBanName": null,
                                "cashTao": null,
                                "cashTaoName": null,
                                "cashAttribute": null,
                                "cashAttributeName": null,
                                "totalAmount": null,
                                "jnbProductNo": null,
                                "jnbProductName": null,
                                "matSource": null,
                                "entityCatalog": null
                            }
                        ],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-07-25 10:32:32",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-01-02",
                        "entityCatalog": 1,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-01-02",
                        "remoteCellId": "L-2-1",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "1",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "1000",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-13 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-01-03",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-01-03",
                        "remoteCellId": "L-3-1",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-13 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-01-04",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-01-04",
                        "remoteCellId": "L-4-1",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-25 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-02-01",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-02-01",
                        "remoteCellId": "L-1-2",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "1000",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-13 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-02-02",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-02-02",
                        "remoteCellId": "L-2-2",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-10 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-02-03",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-02-03",
                        "remoteCellId": "L-3-2",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-25 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-02-04",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-02-04",
                        "remoteCellId": "L-4-2",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "1000",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-25 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-03-01",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-03-01",
                        "remoteCellId": "L-1-3",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-13 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-03-04",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-03-04",
                        "remoteCellId": "L-4-3",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-25 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-04-01",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-04-01",
                        "remoteCellId": "L-1-4",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-13 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-04-02",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-04-02",
                        "remoteCellId": "L-2-4",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-10 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-04-03",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-04-03",
                        "remoteCellId": "L-3-4",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-25 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    },
                    {
                        "matBoxIdList": null,
                        "matBoxId": "A01-001-04-04",
                        "entityCatalog": 0,
                        "matType": 0,
                        "matBoxType": 3,
                        "matBoxStatus": 1,
                        "cellId": "A01-001-04-04",
                        "remoteCellId": "L-4-4",
                        "cellType": 1,
                        "cellStatus": 1,
                        "locationId": "",
                        "workStationId": null,
                        "areaId": "C399999-01-01",
                        "shelfId": "C399999-01-01-01",
                        "property": 0,
                        "bindChannel": null,
                        "totalAmount": 0,
                        "boxWeight": "0",
                        "imagePath": "",
                        "aiImage": "",
                        "note": "",
                        "matSkus": [],
                        "matGjs": [],
                        "matPz": [],
                        "todayArranged": null,
                        "matSource": null,
                        "cellEnterTime": "2024-06-25 16:56:15",
                        "qfFlag": "1",
                        "matAttribute": "0"
                    }
                ],
                "onlineFlag": "0"
            },
            {
                "matAttribute": "0",
                "totalAmount": 0,
                "shelfId": "C399999-01-01-02",
                "shelfStatus": 2,
                "qfFlag": "1",
                "shelfType": 0,
                "switchStatus": "0",
                "detail": [],
                "onlineFlag": "0"
            },
            {
                "matAttribute": "0",
                "totalAmount": 0,
                "shelfId": "C399999-01-01-03",
                "shelfStatus": 5,
                "qfFlag": "1",
                "shelfType": 0,
                "switchStatus": "0",
                "detail": [],
                "onlineFlag": "0"
            },
            {
                "matAttribute": "0",
                "totalAmount": 0,
                "shelfId": "C399999-01-01-04",
                "shelfStatus": 1,
                "qfFlag": "1",
                "shelfType": 0,
                "switchStatus": "0",
                "detail": [],
                "onlineFlag": "0"
            },
            {
                "matAttribute": "0",
                "totalAmount": 0,
                "shelfId": "C399999-01-01-05",
                "shelfStatus": 1,
                "qfFlag": "1",
                "shelfType": 2,
                "switchStatus": "0",
                "detail": [],
                "onlineFlag": "0"
            },
            {
                "matAttribute": "0",
                "totalAmount": 0,
                "shelfId": "C399999-01-01-06",
                "shelfStatus": 1,
                "qfFlag": "1",
                "shelfType": 2,
                "switchStatus": "0",
                "detail": [],
                "onlineFlag": "0"
            },
            {
                "matAttribute": "0",
                "totalAmount": 0,
                "shelfId": "C399999-01-01-07",
                "shelfStatus": 1,
                "qfFlag": "1",
                "shelfType": 2,
                "switchStatus": "0",
                "detail": [],
                "onlineFlag": "0"
            },
            {
                "matAttribute": "0",
                "totalAmount": 0,
                "shelfId": "C399999-01-01-08",
                "shelfStatus": 1,
                "qfFlag": "1",
                "shelfType": 2,
                "switchStatus": "0",
                "detail": [],
                "onlineFlag": "0"
            },
            {
                "matAttribute": "0",
                "totalAmount": 0,
                "shelfId": "C399999-01-01-09",
                "shelfStatus": 0,
                "qfFlag": "1",
                "shelfType": 2,
                "switchStatus": "0",
                "detail": [],
                "onlineFlag": "0"
            }
        ]
    };
    if (method === 'DELETE') {
        returnData = {
            "retCode": '999999',
            "retMsg": "不支持DELETE方法"
        }
    }
    return JSON.stringify(returnData);
};
